#!/usr/bin/sh

if [ -z "$1" ]
then
    echo "usage:"
    echo "fixwordpress username"
else
    cd /home/$1/public_html

    echo "rebuilding .htaccess"
    echo "# BEGIN WordPress
# As diretrizes (linhas) entre "BEGIN WordPress" e "END WordPress" são
# geradas dinamicamente e só devem ser modificadas através de filtros do WordPress.
# Quaisquer alterações nas diretivas entre esses marcadores serão sobrescritas.
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress" > .htaccess

    echo "fixing ownership of $1"
    chown -R $1:$1 *

    echo "fixing permissions of directories"
    find . -type d -exec chmod 755 {} \;

    echo "fixing permissions of files"
    find . -type f -exec chmod 644 {} \;

fi
