#!/usr/bin/sh

if [ $# -ne 1 ]
then
    echo "usage:"
    echo "loademail domain"
else
    oldserverdir=/root/mailsync
    domain=$1
    basedir=/home/vmail/$domain

    origin=agenciaboz:$oldserverdir/$domain.zip
    echo "downloading emails from $origin into $basedir"

    cd $basedir
    scp $origin .
fi