#!/bin/bash

# Set the root directory
ROOT_DIR="/home/vmail/casaludica.com.br"
OLD_DIR="${ROOT_DIR}/0_VELHO"

# Check if OLD_DIR exists
if [ ! -d "$OLD_DIR" ]; then
    echo "Directory $OLD_DIR does not exist."
    exit 1
fi

# Iterate through each directory in 0_VELHO
for dir in "$OLD_DIR"/*; do
    if [ -d "$dir" ]; then
        # Extract the directory name
        DIR_NAME=$(basename "$dir")
        TARGET_DIR="${ROOT_DIR}/${DIR_NAME}/Maildir"

        echo "Copying $DIR_NAME"

        # Create the target directory if it does not exist
        mkdir -p "$TARGET_DIR"

       # Ensuring all files and sub-directories, including hidden ones, are copied
        rsync -aHAXv --no-compress --info=progress2 "$dir/" "$TARGET_DIR/"


        # Prompt user input
        echo "Account ${DIR_NAME} was copied."
        # Remove the original directory
        rm -rf "$dir"
        echo "Directory $dir deleted."
    fi
done

echo "All processes completed."