#!/bin/bash

if [ $# -ne 1 ]
then
    echo "usage:"
    echo "loadwordpress domain"
else
    oldserverdir=/root/wpsync
    domain=$1

    # create cyberpanel website
    echo "creating website on cyberpanel"
    cyberpanel createWebsite --package Default --owner admin --domainName $domain --email mizael@agenciazop.com.br --php 8.1 --openBasedir 1
    basedir=/home/$domain/public_html
    echo

    echo "creating database"
    account="${domain%%.com*}"
    account="${account//./_}_wordpress"
    password_lenght=10
    db_password=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c "$password_lenght")
    cyberpanel createDatabase --databaseWebsite $domain --dbName $account --dbUsername $account --dbPassword $db_password

    # echo "you should have created every email accounts before running this script"
    # echo "continue?"
    # read input

    origin=agenciaboz:$oldserverdir/$domain.zip
    echo "downloading files from $origin into $basedir"
    cd $basedir
    scp $origin .

    echo "extracting files"
    unzip -q $domain.zip
    rm -rf $domain.zip

    echo
    echo "importing database data"
    mysql $account < $domain.sql

    echo
    echo "setting up wp-config.php for new database"
    wp_config_file="./wp-config.php"

    # Use sed to replace the values in the wp-config.php file
    sed -i "s/define( 'DB_NAME', '.*' );/define( 'DB_NAME', '$account' );/" "$wp_config_file"
    sed -i "s/define( 'DB_USER', '.*' );/define( 'DB_USER', '$account' );/" "$wp_config_file"
    sed -i "s/define( 'DB_PASSWORD', '.*' );/define( 'DB_PASSWORD', '$db_password' );/" "$wp_config_file"

    echo
    echo "setting up permissions"
    user=$(stat -c "%U" "$basedir")
    fixwordpress $user

    echo "finished"
    exit 0
fi