#!/bin/bash

if [ $# -ne 2 ]
then
    echo "usage:"
    echo "loadwpsubdomain domain subdomain"
else
    oldserverdir=/root/wpsync
    domain=$1
    subdomain=$2

    echo "creating subdomain on cyberpanel"
    cyberpanel createChild --masterDomain $domain --childDomain $subdomain --owner admin --php 8.1 --openBasedir 1
    basedir=/home/$domain/$subdomain
    echo

    echo "creating database"
    account="${subdomain%%.com*}"
    account="${account//./_}_wordpress"
    password_lenght=10
    db_password=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c "$password_lenght")
    cyberpanel createDatabase --databaseWebsite $domain --dbName $account --dbUsername $account --dbPassword $db_password

    origin=agenciaboz:$oldserverdir/$subdomain.zip
    echo "downloading files from $origin into $basedir"
    cd $basedir
    scp $origin .

    echo "extracting files"
    unzip -q $subdomain.zip
    rm -rf $subdomain.zip

    echo
    echo "importing database data"
    mysql $account < $subdomain.sql
    rm -rf $subdomain.sql

    echo
    echo "setting up wp-config.php for new database"
    wp_config_file="./wp-config.php"

    sed -i "s/define( 'DB_NAME', '.*' );/define( 'DB_NAME', '$account' );/" "$wp_config_file"
    sed -i "s/define( 'DB_USER', '.*' );/define( 'DB_USER', '$account' );/" "$wp_config_file"
    sed -i "s/define( 'DB_PASSWORD', '.*' );/define( 'DB_PASSWORD', '$db_password' );/" "$wp_config_file"

    echo
    echo "setting up permissions"
    fixwpsubdomain $domain $subdomain

    echo "finished"
    exit 0
fi