#!/usr/bin/sh

if [ $# -ne 2 ]
then
    echo "usage:"
    echo "pkgemail username domain"
else
    savedir=/root/mailsync
    [ ! -d "$savedir" ] && mkdir "$savedir"

    user=$1
    domain=$2

    mailboxes="/home/$user/mail/$domain"
    destination=$savedir/$user.zip

    echo "compressing $mailboxes into $destination"
    zip -r $destination $mailboxes/*
fi