#!/usr/bin/sh

if [ $# -ne 2 ]
then
    echo "usage:"
    echo "pkgwordpress username domain"
else
    savedir=/root/wpsync
    [ ! -d "$savedir" ] && mkdir "$savedir"

    echo "packaging $1"

    cd /home/$1/public_html
    pwd

    dbname=$(grep "DB_NAME" wp-config.php | cut -d "'" -f 4)
    echo "database name: $dbname"

    echo "dumping database"
    mysqldump $dbname > "${2}.sql"

    echo "compressing files"
    zip -rq  "${savedir}/${2}.zip" *

    echo "finished. run this command on the new server"
    echo "loadwordpress $2"
fi

